### PR TITLE
Allow doctrine/persistence 3

### LINKED ISSUE #20: Support for doctrine/persistence 3.0
`doctrine/persistence` 3.0 has been released: https://github.com/doctrine/persistence/blob/3.0.0/UPGRADE.md

It would be great for this bundle to be compatible with it.

### PR DESCRIPTION
**Pull request by franmomu**
Doing a quick search I haven't found any issues, let see if tests pass.

Closes #20

### CODE REVIEW

**Comment by curry684** [comment]
Change seems good, ship it   :)

**Comment by krstns** [comment]
Any chance this could be released?

**Comment by nayodahl** [comment]
Hello @theofidry , is there any chance you could approve/release this please ?

**Comment by Thylk** [comment]
Hello, my first comment ever on GitHub. I'm running into the same problem as doctrine/persistence 3.0 is not supported yet. I would have to downgrade it to install alice...
Can this fix be merged if all is good? Thanks :)

**Comment by tacman** [comment]
Any downside to merging this?  If there's an issue (and there doesn't seem to be), users could continue to use ^2.

**Comment by franmomu** [comment]
friendly ping @theofidry if you can take a look at this would be appreciated.

**Comment by hectorprats** [comment]
Please, merge...

**Comment by akalineskou** [comment]
Tried it in a symfony 6, php 8.1 project using this branch and there were no errors.

**Comment by theofidry** [comment]
Thank you @franmomu and the testers

**Pull request merged**
